spring:
  application:
    name: code-as-review

  datasource:
    url: jdbc:mysql://localhost:3306/code_as_review?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: password@mysql
    driver-class-name: com.mysql.cj.jdbc.Driver

