/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedCredentialsIndexRouteImport } from './routes/_authenticated/credentials/index'
import { Route as AuthenticatedIssuesIndexRouteImport } from './routes/_authenticated/issues/index'
import { Route as AuthenticatedIssuesIssueIdRouteImport } from './routes/_authenticated/issues/$issueId'
import { Route as AuthenticatedModelConfigsIndexRouteImport } from './routes/_authenticated/model-configs/index'
import { Route as AuthenticatedRepositoriesIndexRouteImport } from './routes/_authenticated/repositories/index'
import { Route as AuthenticatedReviewsIndexRouteImport } from './routes/_authenticated/reviews/index'
import { Route as AuthenticatedReviewsReviewIdRouteImport } from './routes/_authenticated/reviews/$reviewId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCredentialsIndexRoute =
  AuthenticatedCredentialsIndexRouteImport.update({
    id: '/credentials/',
    path: '/credentials/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIssuesIndexRoute =
  AuthenticatedIssuesIndexRouteImport.update({
    id: '/issues/',
    path: '/issues/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIssuesIssueIdRoute =
  AuthenticatedIssuesIssueIdRouteImport.update({
    id: '/issues/$issueId',
    path: '/issues/$issueId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedModelConfigsIndexRoute =
  AuthenticatedModelConfigsIndexRouteImport.update({
    id: '/model-configs/',
    path: '/model-configs/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRepositoriesIndexRoute =
  AuthenticatedRepositoriesIndexRouteImport.update({
    id: '/repositories/',
    path: '/repositories/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReviewsIndexRoute =
  AuthenticatedReviewsIndexRouteImport.update({
    id: '/reviews/',
    path: '/reviews/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReviewsReviewIdRoute =
  AuthenticatedReviewsReviewIdRouteImport.update({
    id: '/reviews/$reviewId',
    path: '/reviews/$reviewId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/issues/$issueId': typeof AuthenticatedIssuesIssueIdRoute
  '/reviews/$reviewId': typeof AuthenticatedReviewsReviewIdRoute
  '/credentials/': typeof AuthenticatedCredentialsIndexRoute
  '/issues/': typeof AuthenticatedIssuesIndexRoute
  '/model-configs/': typeof AuthenticatedModelConfigsIndexRoute
  '/repositories/': typeof AuthenticatedRepositoriesIndexRoute
  '/reviews/': typeof AuthenticatedReviewsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/': typeof AuthenticatedIndexRoute
  '/issues/$issueId': typeof AuthenticatedIssuesIssueIdRoute
  '/reviews/$reviewId': typeof AuthenticatedReviewsReviewIdRoute
  '/credentials': typeof AuthenticatedCredentialsIndexRoute
  '/issues': typeof AuthenticatedIssuesIndexRoute
  '/model-configs': typeof AuthenticatedModelConfigsIndexRoute
  '/repositories': typeof AuthenticatedRepositoriesIndexRoute
  '/reviews': typeof AuthenticatedReviewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/issues/$issueId': typeof AuthenticatedIssuesIssueIdRoute
  '/_authenticated/reviews/$reviewId': typeof AuthenticatedReviewsReviewIdRoute
  '/_authenticated/credentials/': typeof AuthenticatedCredentialsIndexRoute
  '/_authenticated/issues/': typeof AuthenticatedIssuesIndexRoute
  '/_authenticated/model-configs/': typeof AuthenticatedModelConfigsIndexRoute
  '/_authenticated/repositories/': typeof AuthenticatedRepositoriesIndexRoute
  '/_authenticated/reviews/': typeof AuthenticatedReviewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/issues/$issueId'
    | '/reviews/$reviewId'
    | '/credentials/'
    | '/issues/'
    | '/model-configs/'
    | '/repositories/'
    | '/reviews/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/'
    | '/issues/$issueId'
    | '/reviews/$reviewId'
    | '/credentials'
    | '/issues'
    | '/model-configs'
    | '/repositories'
    | '/reviews'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/'
    | '/_authenticated/issues/$issueId'
    | '/_authenticated/reviews/$reviewId'
    | '/_authenticated/credentials/'
    | '/_authenticated/issues/'
    | '/_authenticated/model-configs/'
    | '/_authenticated/repositories/'
    | '/_authenticated/reviews/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/credentials/': {
      id: '/_authenticated/credentials/'
      path: '/credentials'
      fullPath: '/credentials/'
      preLoaderRoute: typeof AuthenticatedCredentialsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/issues/': {
      id: '/_authenticated/issues/'
      path: '/issues'
      fullPath: '/issues/'
      preLoaderRoute: typeof AuthenticatedIssuesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/issues/$issueId': {
      id: '/_authenticated/issues/$issueId'
      path: '/issues/$issueId'
      fullPath: '/issues/$issueId'
      preLoaderRoute: typeof AuthenticatedIssuesIssueIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/model-configs/': {
      id: '/_authenticated/model-configs/'
      path: '/model-configs'
      fullPath: '/model-configs/'
      preLoaderRoute: typeof AuthenticatedModelConfigsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/repositories/': {
      id: '/_authenticated/repositories/'
      path: '/repositories'
      fullPath: '/repositories/'
      preLoaderRoute: typeof AuthenticatedRepositoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reviews/': {
      id: '/_authenticated/reviews/'
      path: '/reviews'
      fullPath: '/reviews/'
      preLoaderRoute: typeof AuthenticatedReviewsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reviews/$reviewId': {
      id: '/_authenticated/reviews/$reviewId'
      path: '/reviews/$reviewId'
      fullPath: '/reviews/$reviewId'
      preLoaderRoute: typeof AuthenticatedReviewsReviewIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedIssuesIssueIdRoute: typeof AuthenticatedIssuesIssueIdRoute
  AuthenticatedReviewsReviewIdRoute: typeof AuthenticatedReviewsReviewIdRoute
  AuthenticatedCredentialsIndexRoute: typeof AuthenticatedCredentialsIndexRoute
  AuthenticatedIssuesIndexRoute: typeof AuthenticatedIssuesIndexRoute
  AuthenticatedModelConfigsIndexRoute: typeof AuthenticatedModelConfigsIndexRoute
  AuthenticatedRepositoriesIndexRoute: typeof AuthenticatedRepositoriesIndexRoute
  AuthenticatedReviewsIndexRoute: typeof AuthenticatedReviewsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedIssuesIssueIdRoute: AuthenticatedIssuesIssueIdRoute,
  AuthenticatedReviewsReviewIdRoute: AuthenticatedReviewsReviewIdRoute,
  AuthenticatedCredentialsIndexRoute: AuthenticatedCredentialsIndexRoute,
  AuthenticatedIssuesIndexRoute: AuthenticatedIssuesIndexRoute,
  AuthenticatedModelConfigsIndexRoute: AuthenticatedModelConfigsIndexRoute,
  AuthenticatedRepositoriesIndexRoute: AuthenticatedRepositoriesIndexRoute,
  AuthenticatedReviewsIndexRoute: AuthenticatedReviewsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
